---
tasks:
- name: models collection
  scripts:
    rspec:
      body: bundle exec rspec "spec/models/collection_spec.rb"
- name: models media_entry
  scripts:
    rspec:
      body: bundle exec rspec "spec/models/media_entry_spec.rb"
- name: models media_file
  scripts:
    rspec:
      body: bundle exec rspec "spec/models/media_file_spec.rb"
- name: models relations resource_media_entry_arc
  scripts:
    rspec:
      body: bundle exec rspec "spec/models/relations/resource_media_entry_arc_spec.rb"
