- name: Bundle
  shell: su -l -s /bin/bash -c 'source /etc/profile.d/rbenv-load.sh 
          && rbenv-load 
          && cd {{madek_root}}
          && export RAILS_ENV={{rails_env}} 
          && export RBENV_VERSION={{item.version}} 
          && bundle install --deployment' madek
         executable=/bin/bash
  with_items: rubies


- name: Setup madek dirs
  shell:  su -l -s /bin/bash -c 'source /etc/profile.d/rbenv-load.sh 
            && rbenv-load 
            && cd {{madek_root}}
            && export RAILS_ENV={{rails_env}} 
            && export RBENV_VERSION={{mri_ruby_version}} 
            && bundle exec rake madek:setup:dirs' madek
          executable=/bin/bash

- name: Migrate
  shell:  su -l -s /bin/bash -c 'source /etc/profile.d/rbenv-load.sh 
            && rbenv-load 
            && cd {{madek_root}}
            && export RAILS_ENV={{rails_env}} 
            && export RBENV_VERSION={{mri_ruby_version}} 
            && bundle exec rake db:create db:migrate' madek
          executable=/bin/bash

- name: Precompile assets 
  shell:  su -l -s /bin/bash -c 'source /etc/profile.d/rbenv-load.sh 
            && rbenv-load 
            && cd {{madek_root}}
            && export RAILS_ENV={{rails_env}} 
            && export RBENV_VERSION={{mri_ruby_version}} 
            && rm -rf public/assets/*"
            && rm -rf tmp/cache/*"
            && bundle exec rake assets:precompile' madek
          executable=/bin/bash

- name: Enable site
  command: a2ensite madek 

- name: Reload apache
  service: name=apache2
           state=reloaded
