default: &default
  adapter: postgresql
  encoding: utf8
  username: domina
  password: domina

test: 
  <<: *default
  database: madek_test

personas: 
  <<: *default 
  database: madek_personas_test
