tasks:

  env:
    name: Show environment
    scripts:
      main:
        body: env | sort

  list_dir:
    name: List working directory
    scripts:
      main:
        body: ls -lah

  git_log:
    name: Git log of last commits
    scripts:
      main:
        body: git log -n 3

  rake_routes: # this catches strange bugs (ie. server broken but not in rspec)
    name: Rake Routes
    environment_variables:
      RAILS_ENV: production
    scripts:
      main:
        body: rake routes
