         
- name: Disable default site
  command:  a2dissite 000-default
            removes=/etc/apache2/sites-enabled/000-default

- name: Enable site
  command: a2ensite madek 

- name: Enable modules
  shell:  
          a2enmod expires;
          a2enmod headers;
          a2enmod proxy;
          a2enmod proxy_http;
          a2enmod rewrite;
          a2enmod xsendfile;

- name: Enable mod-passenger
  command: a2enmod passenger

- name: Restart
  service: name=apache2
           state=restarted

- name: Reload
  service: name=apache2
           state=reloaded

